# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  schedule:
    - cron: '5,20,35,50 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run data collection
      run: |
        github-to-sqlite commits django.db django/django
    - name: Clone Django
      run: |
        git clone https://github.com/django/django
    - name: run benchmarks
      run: |
        python run_benchmarks.py
        python save_data.py
    - uses: stefanzweifel/git-auto-commit-action@v4.6.0
      name: Commit changes
      with:
        commit_message: Automatic update to database
        file_pattern: django.db
    - name: Publish to heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:login && heroku plugins:install heroku-builds && datasette publish heroku django.db --install=datasette-vega --name djangobench-tracker --metadata metadata.yml
        heroku ps:stop -a djangobench-tracker web
